name: Unit and Integration Tests
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Compile
      run: make build-only

    - name: Run Unit Tests
      run: make unit-test

    - name: Run Integration Tests
      run: make integration-test
